spring:
  datasource:
    url: jdbc:mysql://springboot-database.chimyyqw2kxh.ap-northeast-2.rds.amazonaws.com:3306/shop
    username: admin
    password: ewqdsa1927
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:



jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==


naver:
  client:
    id: dFk8xhy076ULcflQdF8l
    secret: 9mr3RhaEPY




kakao:
  restApiKey: d0fc91228613a4484fb3a76d45a74f92